name: CI

on:
  pull_request: ~

jobs:

  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.2', '7.3', '7.4', '8.0' ]
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Run tests
        run: ./vendor/bin/phpunit
