name: Static analysis

on:
  pull_request: ~


jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PHPStan
        uses: actions/cache@v2
        with:
          path: .github/.cache/phpstan/
          key: phpstan-${{ github.sha }}
          restore-keys: phpstan-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: phpstan:0.12.88, cs2pr
          extensions: swoole

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: PHPStan
        run: phpstan analyze --no-progress --error-format=checkstyle | cs2pr

  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache PhpCsFixer
        uses: actions/cache@v2
        with:
          path: .github/.cache/php-cs-fixer/
          key: php-cs-fixer-${{ github.sha }}
          restore-keys: php-cs-fixer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: php-cs-fixer:2.19.0, cs2pr

      - name: PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

  psalm:
    name: Psalm
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Psalm
        uses: actions/cache@v2
        with:
          path: .github/.cache/psalm/
          key: psalm-${{ github.sha }}
          restore-keys: psalm-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none
          tools: vimeo/psalm:4.7.2
          extensions: swoole

      - name: Download dependencies
        uses: ramsey/composer-install@v1

      - name: Psalm
        run: psalm --no-progress --output-format=github
